### PR TITLE
workload profile fix and provider upgrade fixes

### LINKED ISSUE #95: Readme is incorrect
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

_No response_

### (Optional) Module Version

_No response_

### (Optional) Correlation Id

_No response_

### Description

[log_analytics_workspace_destination](https://registry.terraform.io/modules/Azure/avm-res-app-managedenvironment/azurerm/latest#input_log_analytics_workspace_destination)
Description: Destination for Log Analytics (options: 'log-analytics', 'azuremonitor', 'none').

Type: string

Default: "log-analytics"

azuremonitor should be **azure-monitor**

### PR DESCRIPTION
**Pull request by kewalaka**
From @alefteris 

Setting a workload profile wasn't working, because the check for consumption profile to set workload_profiles_consumption_enabled didn't account for the fact that the workload_profile variable includes also the max/min count with default values. So I fixed this part. Also fixed is the part that sets the workloadProfiles for the azapi resource to use the correct format.

The rest of the changes are white-space changes from running the avm pre-commit and adding the modtm provider that was needed for the module to work, because of previous commits in main the branch.

From @kewalaka 

Added linting fixes to appease pr-check

Additional PR merged from #110 :

Breaking changes (outputs, dapr components & storage references)

- removal of the 'resource' output as required by the AVM spec and #98
- removal of any non-computed outputs as per the AVM spec
- the `dapr_component` and `storage` component have been moved into submodules - this will cause these to be re-created if they are used.  The relevant dapr & storage examples illustrate how to use `moved` blocks to avoid resource recreation if desirable.   Note that this is a reference to storage volumes, not the actual storage being presented.
 
I don't think it is possible to do have the `moved` block within the module because you can't move a resource to a module.

This PR also introduces;

- optional support for AzureRM v4 and AzAPI v2 (v3/v1 remain supported)
- additional test example to exercise this
- additional outputs.tf files in the examples
- update to resource manager API (from 2023-05-01 to 2024-03-01)
- removal of data source for resource group, to avoid 'evil' problems.
- name for managed infrastructure resource group name is honoured if supplied.

Fixes #95, #96, #98, #105, #106, #107, #108, #109

### CODE REVIEW

**Comment by kewalaka** [comment]
@segraef do you have any feedback?  I don't believe I can trigger the E2E run

**Comment by segraef** [comment]
this PR might need a rebase once https://github.com/Azure/Azure-Verified-Modules-Grept/actions/runs/12020307643 creates a fresh chore PR to sync the repo with latest runner pool config

**Comment by segraef** [comment]
fixed via https://github.com/Azure/terraform-azurerm-avm-res-app-managedenvironment/pull/103, please rebase, thanks

**Comment by kewalaka** [comment]
please merge #111 into this branch before running tests thanks

**Comment by segraef** [comment]
As discussed, check the conflicts, otherwise, recreate the PR, thanks.

**Comment by kewalaka** [comment]
The issues seems to be in the azure wp-fix branch, as illustrated via screenshot there is no conflict on a clone.  Would you delete this branch please and make a new dev branch, or if you can give me write access i can fix.

**Review by segraef — APPROVED** [review]

**Pull request merged**
